### PR TITLE
Un-ignore create.sh script

### PR DESCRIPTION
**Pull request by pacostas**
## Summary

This PR has been merged https://github.com/paketo-buildpacks/github-config/pull/899, so now we can sync with github-config

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by pacostas** [comment]
@mhdawson

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@pacostas the tests seem to be failing, can you take a look?

**Comment by pacostas** [comment]
Yeap, something has happened lately with the tests on the stacks in general. I'll take a look

**Comment by pacostas** [comment]
@mhdawson 
This seems to be the error
```
Copying blob 98be1b9a299c [--------------------------------------] 384.0KiB / 39.3MiB | 820.7 KiB/s
Copying blob 5208a9ec700e [>-------------------------------------] 8.0b / 602.0b | 568.1 KiB/s
FATA[0000] writing blob: io: read/write on closed pipe 
```
Which happens while it pushes the image to docker daemon with below command
```
skopeo copy "oci-archive:/home/costas/Desktop/ubi-base-stack/build/build.oci" "docker-daemon:build-image-c3f2fc61-97df-4e0a-9b70-7d3182abe92a:latest"
```

running the above command with sudo in front of it, I get below error 
```
FATA[0000] writing blob: starting a load operation in docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version 
```

So lets say skopeo is a bit outdated based on this comment https://github.com/containers/skopeo/issues/2251#issuecomment-1991834580 

Using docker to load the image is possible but docker does not support .oci files. 

Although there is a solution, pushing the .oci archive to registry without first loading to docker daemon.  So here
https://github.com/paketo-community/ubi-base-stack/blob/ad2729e61746d1758109d64e31a86e3a146e3677/internal/utils/utils.go#L18-L29

instead of loading the image on the docker daemon and also loading the image on local registry, we can load the image to local registry, and if we want the image also present on docker daemon, we can just pull it.

**Comment by pacostas** [comment]
This PR will make the tests pass https://github.com/paketo-community/ubi-base-stack/pull/84

**Pull request merged**
