### PR TITLE
Polling ubi images - fixing edge case where sha files are not present

### PR DESCRIPTION
**Pull request by pacostas**
## Summary

In case of there are no sha files, as for example on the current release, the action tries to read a file that does not exists and as a result throws an error. This PR adds a check if the file exists before reading it. In case the file does not exist, sets the value of the sha variable to an empty string in order to be updated on the next steps

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by pacostas** [comment]
@sophiewigmore This error did also happen once in my remote repo. I'm not able to reproduce it locally, seems like it has to do with the availability of the server.

**Comment by sophiewigmore** [comment]
thanks for the fix! and yea, the tests have been failing across all of our paketo stack repos.. not sure what's up. I'll investigate the fix for the test

**Review by sophiewigmore — APPROVED** [review]

**Comment by sophiewigmore** [comment]
I think it might have to do with the recent jam release but I'm testing that theory now.

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by robdimsdale — APPROVED** [review]

**Pull request merged**
